// Auth actions
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const SWITCH_LOGIN_SIGNUP = 'SWITCH_LOGIN_SIGNUP'

// Message actions
export const LOAD_THREAD_LIST_ATTEMPT = 'LOAD_THREAD_LIST_ATTEMPT'
export const LOAD_THREAD_LIST_FAILURE = 'LOAD_THREAD_LIST_FAILURE'
export const LOAD_THREAD_LIST_SUCCESS = 'LOAD_THREAD_LIST_SUCCESS'

export const INITIAL_LOAD_MESSAGES_ATTEMPT = 'INITIAL_LOAD_MESSAGES_ATTEMPT'
export const INITIAL_LOAD_MESSAGES_FAILURE = 'INITIAL_LOAD_MESSAGES_FAILURE'
export const INITIAL_LOAD_MESSAGES_SUCCESS = 'INITIAL_LOAD_MESSAGES_SUCCESS'

export const LOAD_NEW_MESSAGES_ATTEMPT = 'LOAD_NEW_MESSAGES_ATTEMPT'
export const LOAD_NEW_MESSAGES_FAILURE = 'LOAD_NEW_MESSAGES_FAILURE'
export const LOAD_NEW_MESSAGES_SUCCESS = 'LOAD_NEW_MESSAGES_SUCCESS'

export const LOAD_OLD_MESSAGES_ATTEMPT = 'LOAD_OLD_MESSAGES_ATTEMPT'
export const LOAD_OLD_MESSAGES_FAILURE = 'LOAD_OLD_MESSAGES_FAILURE'
export const LOAD_OLD_MESSAGES_SUCCESS = 'LOAD_OLD_MESSAGES_SUCCESS'

export const SEND_MESSAGE_ATTEMPT = 'SEND_MESSAGE_ATTEMPT'
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'

export const SUBMIT_PROMPT_RESPONSE_ATTEMPT = 'SUBMIT_PROMPT_RESPONSE_ATTEMPT'
export const SUBMIT_PROMPT_RESPONSE_FAILURE = 'SUBMIT_PROMPT_RESPONSE_FAILURE'
export const SUBMIT_PROMPT_RESPONSE_SUCCESS = 'SUBMIT_PROMPT_RESPONSE_SUCCESS'

// Contacts Actions
export const LOAD_CONTACTS_ATTEMPT = 'LOAD_CONTACTS_ATTEMPT'
export const LOAD_CONTACTS_FAILURE = 'LOAD_CONTACTS_FAILURE'
export const LOAD_CONTACTS_SUCCESS = 'LOAD_CONTACTS_SUCCESS'

export const LOAD_CONTACT_CARD_ATTEMPT = 'LOAD_CONTACT_CARD_ATTEMPT'
export const LOAD_CONTACT_CARD_FAILURE = 'LOAD_CONTACT_CARD_FAILURE'
export const LOAD_CONTACT_CARD_SUCCESS = 'LOAD_CONTACT_CARD_SUCCESS'

export const NEW_CONTACT_ATTEMPT = 'NEW_CONTACT_ATTEMPT'
export const NEW_CONTACT_FAILURE = 'NEW_CONTACT_FAILURE'
export const NEW_CONTACT_SUCCESS = 'NEW_CONTACT_SUCCESS'

// Nav Actions
export const NAV_TO_HOME = 'NAV_TO_HOME'
