// Auth actions
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const SWITCH_LOGIN_SIGNUP = 'SWITCH_LOGIN_SIGNUP'

export const CHANGE_PASSWORD_ATTEMPT = 'CHANGE_PASSWORD_ATTEMPT'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'

// Message actions
export const LOAD_THREAD_LIST_ATTEMPT = 'LOAD_THREAD_LIST_ATTEMPT'
export const LOAD_THREAD_LIST_FAILURE = 'LOAD_THREAD_LIST_FAILURE'
export const LOAD_THREAD_LIST_SUCCESS = 'LOAD_THREAD_LIST_SUCCESS'

export const INITIAL_LOAD_MESSAGES_ATTEMPT = 'INITIAL_LOAD_MESSAGES_ATTEMPT'
export const INITIAL_LOAD_MESSAGES_FAILURE = 'INITIAL_LOAD_MESSAGES_FAILURE'

export const INITIAL_LOAD_CHAT_ONLY_MESSAGES_SUCCESS = 'INITIAL_LOAD_CHAT_ONLY_MESSAGES_SUCCESS'
export const INITIAL_LOAD_REFLECTION_ONLY_MESSAGES_SUCCESS = 'INITIAL_LOAD_REFLECTION_ONLY_MESSAGES_SUCCESS'
export const INITIAL_LOAD_REFLECTION_AND_CHAT_MESSAGES_SUCCESS = 'INITIAL_LOAD_REFLECTION_AND_CHAT_MESSAGES_SUCCESS'

export const LOAD_NEW_MESSAGES_ATTEMPT = 'LOAD_NEW_MESSAGES_ATTEMPT'
export const LOAD_NEW_MESSAGES_FAILURE = 'LOAD_NEW_MESSAGES_FAILURE'

export const LOAD_NEW_CHAT_ONLY_MESSAGES_SUCCESS = 'LOAD_NEW_CHAT_ONLY_MESSAGES_SUCCESS'
export const LOAD_NEW_REFLECTION_ONLY_MESSAGES_SUCCESS = 'LOAD_NEW_REFLECTION_ONLY_MESSAGES_SUCCESS'
export const LOAD_NEW_REFLECTION_AND_CHAT_MESSAGES_SUCCESS = 'LOAD_NEW_REFLECTION_AND_CHAT_MESSAGES_SUCCESS'

export const LOAD_OLD_MESSAGES_ATTEMPT = 'LOAD_OLD_MESSAGES_ATTEMPT'
export const LOAD_OLD_MESSAGES_FAILURE = 'LOAD_OLD_MESSAGES_FAILURE'

export const LOAD_OLD_CHAT_ONLY_MESSAGES_SUCCESS = 'LOAD_OLD_CHAT_ONLY_MESSAGES_SUCCESS'
export const LOAD_OLD_REFLECTION_ONLY_MESSAGES_SUCCESS = 'LOAD_OLD_REFLECTION_ONLY_MESSAGES_SUCCESS'
export const LOAD_OLD_REFLECTION_AND_CHAT_MESSAGES_SUCCESS = 'LOAD_OLD_REFLECTION_AND_CHAT_MESSAGES_SUCCESS'

export const SEND_MESSAGE_ATTEMPT = 'SEND_MESSAGE_ATTEMPT'
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'

export const SUBMIT_PROMPT_RESPONSE_ATTEMPT = 'SUBMIT_PROMPT_RESPONSE_ATTEMPT'
export const SUBMIT_PROMPT_RESPONSE_FAILURE = 'SUBMIT_PROMPT_RESPONSE_FAILURE'
export const SUBMIT_PROMPT_RESPONSE_SUCCESS = 'SUBMIT_PROMPT_RESPONSE_SUCCESS'

// Nav Actions
export const NAV_TO_HOME = 'NAV_TO_HOME'
